sudo: false
language: node_js
node_js:
  - '10'
  - '11'
  - '12'
branches:
  only:
    - master
    - /^greenkeeper/.*$/
cache:
  directories:
    - node_modules
install:
  - yarn
after_script:
  - cat ./coverage/lcov.info | coveralls
