sudo: false
language: node_js
node_js:
  - '10'
branches:
  only:
    - master
    - /^greenkeeper/.*$/
cache:
  directories:
    - node_modules
install:
  - yarn
script:
  - yarn test
after_script:
  - cat ./coverage/lcov.info | coveralls
